version: '3.8'

services:

  php:
    container_name: php
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/var/www/html
      - ./public:/var/www/html/public
    working_dir: /var/www/html/public
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    networks:
      - breastplate_network
    ports:
      - "80:80"

  db:
    container_name: db
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: breastplate
    volumes:
      - db_data:/var/lib/mysql
      - ./resources/sql:/docker-entrypoint-initdb.d:ro
    networks:
      - breastplate_network

volumes:
  db_data:

networks: # Rede de comunicação entre os containers
  breastplate_network:
    driver: bridge